import os
import requests
import json
import sqlite3
import pandas as pd
from groq import Groq

# --- 1. THE BRAIN (Groq Llama 3.3) ---
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# --- 2. THE ORGANS (Tools) ---

def execute_snow_leopard_query(query):
    file_id = os.environ.get("SNOW_LEOPARD_FILE_ID")
    api_key = os.environ.get("SNOW_LEOPARD_API_KEY")
    
    if not file_id or not api_key:
        return "Error: Snow Leopard keys are not exported in the terminal."

    url = f"https://try.snowleopard.ai/api/v1/datafiles/{file_id}/chat/"
    headers = {"Authorization": f"Bearer {api_key}"}
    payload = {"message": query}
    
    try:
        r = requests.post(url, headers=headers, json=payload)
        if r.status_code != 200:
            return f"Snow Leopard Server Error ({r.status_code}): {r.text}"
        return r.json().get("response", "No data found in the response.")
    except Exception as e:
        return f"Database connection error: {e}"

def execute_vision_tool(image_data):
    return "Vision analysis complete: [Placeholder]"

def execute_messaging_tool(content, recipient):
    return f"Message sent successfully to {recipient}!"

# ORGAN D UPGRADE: Now it executes real SQL generated by Groq!
def execute_local_sqlite_query(sql_query):
    try:
        conn = sqlite3.connect('hackathon_database.db')
        
        # Safety net: If Groq forgets to write SQL and writes text instead
        if "SELECT" not in sql_query.upper():
            sql_query = "SELECT * FROM user_data LIMIT 10"
            
        df = pd.read_sql_query(sql_query, conn)
        
        # Stop massive tables from blowing up Groq's token limit
        if len(df) > 50:
            df = df.head(50)
            
        return f"Raw Database Results:\n{df.to_markdown()}"
    except Exception as e:
        return f"SQL Error generated by agent: {e}"

# --- 3. THE PARSER (Now Extracts JSON from Chatty Text) ---
def parse_and_execute(llm_response):
    try:
        # THE FIX: Find where the JSON actually starts and ends
        start_idx = llm_response.find('{')
        end_idx = llm_response.rfind('}')
        
        if start_idx != -1 and end_idx != -1:
            clean_json_string = llm_response[start_idx:end_idx+1]
        else:
            clean_json_string = llm_response # Fallback just in case
            
        decision = json.loads(clean_json_string)
        tool = decision.get("tool") or decision.get("name")
        args = decision.get("args") or decision.get("parameters", {})
        
        if tool == "query_live_data":
            return tool, execute_snow_leopard_query(args.get("query", ""))
        elif tool == "query_local_data":
            return tool, execute_local_sqlite_query(args.get("sql_query", args.get("query", "")))
        elif tool == "analyze_poster":
            return tool, execute_vision_tool(args)
        elif tool == "send_message":
            return tool, execute_messaging_tool(args.get("msg"), args.get("to"))
        elif tool == "direct_response":
            return tool, args.get("text", "I'm not sure how to respond to that.")
        else:
            return "error", f"Error: The Brain tried to use an unknown tool: {tool}"
            
    except json.JSONDecodeError:
        return "error", f"Error: Brain did not output valid JSON. Raw output: {llm_response}"
# --- 4. THE COMMAND CENTER ---
def ask_agent(user_input, chat_history=None, available_columns="Unknown", active_mode="Cloud"):
    
    mode_instruction = ""
    if "Cloud" in active_mode:
        mode_instruction = "You are currently in CLOUD mode. Use 'query_live_data' for remote queries."
    else:
        # We tell it the exact table name so it can write perfect SQL
        mode_instruction = f"You are currently in LOCAL mode. The SQLite table is named 'user_data'. The columns are: {available_columns}."

    system_prompt = f"""You are an elite AI Data Analyst. 
    {mode_instruction}
    
    You have 5 tools available:
    1. 'query_live_data' - args: {{"query": "search text"}}
    2. 'query_local_data' - args: {{"sql_query": "A VALID SQLITE SELECT QUERY. e.g. SELECT * FROM user_data WHERE..."}}
    3. 'analyze_poster' - args: {{"image_url": "url"}}
    4. 'send_message' - args: {{"msg": "text", "to": "recipient"}}
    5. 'direct_response' - args: {{"text": "Your reply."}}
    
    CRITICAL INSTRUCTIONS:
    - If the user asks for local data, you MUST write a valid SQL query for the 'query_local_data' tool. 
    
    OUTPUT FORMAT:
    You MUST output ONLY a valid JSON object. Include a "thought" first.
    {{
        "thought": "your logic",
        "tool": "the_tool",
        "args": {{"key": "value"}}
    }}"""

    messages_payload = [{"role": "system", "content": system_prompt}]
    
    if chat_history:
        for msg in chat_history[-6:]:
            messages_payload.append({"role": msg["role"], "content": str(msg["content"])})
            
    messages_payload.append({"role": "user", "content": user_input})

    try:
        # STEP 1: Let Groq pick the tool
        chat_completion = client.chat.completions.create(
            messages=messages_payload,
            model="llama-3.3-70b-versatile",
            temperature=0.1,
        )
        
        raw_decision = chat_completion.choices[0].message.content
        tool_name, tool_result = parse_and_execute(raw_decision)
        
        # ==========================================
        # STEP 2: THE SYNTHESIS LOOP (NEW!)
        # ==========================================
        # If the tool grabbed database info, send it back to Groq to read!
        if tool_name in ["query_live_data", "query_local_data"] and "Error" not in tool_result:
            synthesis_prompt = f"""The user originally asked: "{user_input}".
            You ran a database query and got this raw data back:
            
            {tool_result}
            
            Please read this data and answer the user's question directly. 
            Do NOT just repeat the raw table. Summarize the findings, highlight trends, and provide meaningful analysis. You may include a small markdown table if it helps explain your points."""
            
            synth_completion = client.chat.completions.create(
                messages=[{"role": "system", "content": synthesis_prompt}],
                model="llama-3.3-70b-versatile",
                temperature=0.4,
            )
            final_answer = synth_completion.choices[0].message.content
            return raw_decision, final_answer
            
        # If it wasn't a database search, just return the direct text
        return raw_decision, tool_result
        
    except Exception as e:
        return '{"error": "API Failure"}', f"Groq API Error: {e}"